/**
 * Curated checklists for the audit's THREE mutually exclusive run paths
 * (see scoring.ts's countedCategories() for the exact routing), every one
 * of them exactly 50 items:
 *
 *   - Visitor has BOTH GA4 and GTM  → 25 GA4 + 25 GTM = 50
 *   - Visitor has exactly ONE of them → 25 (that tool) + 25 (website-code
 *     core, WEBSITE_CODE_CHECKLIST below) = 50
 *   - Visitor has NEITHER            → 50 Website = 50
 *
 * PageSpeed used to be its own 4-point category (PS-1..PS-4), backed by a
 * site-wide PageSpeed Insights sweep. Removed entirely (2026-09-09): the
 * sweep dominated every run's wall-clock time — a sequential mobile+desktop
 * PSI call per discovered page, minutes of it before claude -p even
 * started. The four things it actually scored are now WEB-60..WEB-63,
 * measured from the headless browser's own network/resource data instead,
 * and every other point that used to lean on a Lighthouse audit id now
 * names the browser or static-crawl check that replaces it.
 *
 * Scoring is flat 1 point per item (fail it, lose the point — see
 * scoring.ts), so the checklist size IS the point scale, not a separate
 * weighted system layered on top of it. A run only ever sends ONE path's
 * checklists to claude -p, never a mix beyond what's listed above — the
 * other categories simply don't run that audit at all (this also keeps the
 * prompt well under the OS argv length limit that a combined 114-item
 * version used to hit).
 *
 * GA4_CHECKLIST was rebuilt from scratch against this worker's ACTUAL tool
 * access, not against a generic human-auditor methodology. The original
 * 203-point Master Tracking Audit Framework (`.claude/skills/ga4-gtm-audit`)
 * was written for a human clicking through the GA4/GTM web UI — Preview
 * mode, DebugView, the Template Gallery permissions tab, a backend/ERP
 * system, a client's own KPI doc. None of that exists for a non-interactive
 * `claude -p` run. Every point here was checked against what `ga4-admin-mcp`
 * (full GA4 Admin v1beta/v1alpha + Data API, including the
 * `admin_request`/`data_request` raw passthroughs — not just its ~30
 * dedicated wrapper tools) can actually answer. A point that needed
 * something that tool doesn't expose — live Preview/DebugView, who has
 * Publish access, a shared-link audit trail, a backend finance system, a
 * client's KPI document — was dropped and replaced with an equally real
 * point that IS answerable this way. `validate` on every point below names
 * the actual MCP tool(s) to call, not a UI path to click through — this
 * worker is an LLM with tool access, not a person with a mouse.
 *
 * GA4_CHECKLIST was rewritten a second time (2026-09-06): 15 of its points
 * (the ones that read real report data — former ids GA4-7, GA4-9, GA4-11,
 * GA4-14 through GA4-25) were replaced by GA4-D1 through GA4-D15, open
 * data-driven analysis slots instead of individually pre-specified checks.
 * A fixed "check this exact metric" list caps what gets found at whatever
 * was anticipated when the checklist was written; these 15 slots instead
 * tell Claude to genuinely dig through everything it can pull from the
 * property and surface up to 15 distinct, high-value business insights on
 * its own — see the GA4-D1..GA4-D15 entries' own comment further down and
 * audit-prompt.ts's "GA4 deep-analysis slots" section for the actual
 * instructions. GA4-1 through GA4-6, GA4-8, GA4-10, GA4-12, and GA4-13 stay
 * fixed checks (config hygiene + the two baseline data-health points) — the
 * category still totals exactly 25 points either way.
 *
 * GTM_CHECKLIST (below) is standardized against "GTM Container Audit
 * Checklist: Top 25 High-Impact Checks" (prepared by Gemini Notebook) — see
 * that list's own doc comment further down for how it was adapted to this
 * worker's actual GTM MCP access (a FIXED tool set: accounts/containers/
 * workspaces/workspace-status, tags/triggers/variables CRUD, built-in
 * variables, versions/live-version/publish — no generic passthrough, no
 * permissions/access-binding endpoint, no template-gallery endpoint, no
 * Preview/DebugView).
 *
 * WEBSITE_CHECKLIST (further below) runs on the OTHER two paths — the full
 * 50 items when the visitor has neither GA4 nor GTM, the 25-item
 * WEBSITE_CODE_CHECKLIST slice when they have exactly one. Both of those
 * paths get a real headless browser (chrome-devtools MCP) on top of the
 * static crawl, which is what every point in the list is scoped to now
 * that the PageSpeed sweep is gone.
 */

export interface ChecklistPoint {
  id: string;
  title: string;
  expectedState: string;
  commonFailure: string;
  // How to actually confirm this point one way or the other — not generic
  // advice, the specific check/report/panel to look at. Some validate steps
  // name tools or data this worker structurally doesn't have access to this
  // run (BigQuery, an ad platform's own Events Manager, Screaming Frog); the
  // prompt is told explicitly which access it actually has each run, and to
  // fall back to whatever signal it DOES have (crawl, PageSpeed, general
  // best practice) to still reach a real pass/fail conclusion when the
  // primary validate step's data isn't available — every point always
  // counts toward this run's 50-check total, there is no silent skip any
  // more (see audit-prompt.ts's buildPrompt).
  validate: string;
  severity: "critical" | "medium" | "low";
}

export const GA4_CHECKLIST: ChecklistPoint[] = [
  // ── GA4-D1 through GA4-D15 (2026-09-06 rewrite, moved to the front of
  // this list so they're the first thing read/evaluated each run): open,
  // data-driven analysis slots — NOT a fixed pass/fail check like
  // everything else in this file. They replace what used to be 15
  // individually-specified "real data" points (former ids GA4-7, GA4-9,
  // GA4-11, GA4-14 through GA4-25) because a fixed list of "check this
  // exact metric" points caps what gets found at whatever was anticipated
  // in advance. Each slot is still worth exactly 1 point (see this file's
  // own top doc comment on why checklist size IS the point scale) and still
  // needs its own distinct id so scoring.ts/audit-prompt.ts's flat tally
  // keeps working unchanged.
  //
  // Second rewrite, same day: the first version of these left `validate`
  // fully generic ("see GA4 deep-analysis slots") with zero anchor on WHERE
  // to look — on the very first real run, the model defaulted to re-reading
  // GA4 Admin API config/settings fields (service level, property type,
  // industry category, a Google Ads link's creator email) for almost every
  // slot instead of pulling real report DATA, because config reads are
  // cheaper/easier than a real run_report call. That's worse than what
  // these slots replaced — GA4-1..13 already covers config/settings; a
  // GA4-D slot repeating that isn't one of the 15 distinct insights it's
  // supposed to be. Fix: `validate` below now names the SPECIFIC Data API
  // pull required for that slot (never a settings field) — audit-prompt.ts's
  // "GA4 deep-analysis slots" section has the full instructions and the
  // hard rule against settings-only findings; what the model concludes from
  // that real data (pass/fail, how severe) stays entirely open, which is
  // what keeps these different from GA4-1..13's individually pre-written
  // checks.
  { id: "GA4-D1", title: "Open data-driven finding #1", expectedState: "No fixed expected state — see \"GA4 deep-analysis slots\" in audit-prompt.ts", commonFailure: "N/A — this slot has no single anticipated failure mode by design", validate: "REQUIRED: run_realtime_report (metrics=[activeUsers]) — real-data only, never a settings field. See \"GA4 deep-analysis slots\" in audit-prompt.ts", severity: "medium" },
  { id: "GA4-D2", title: "Open data-driven finding #2", expectedState: "No fixed expected state — see \"GA4 deep-analysis slots\" in audit-prompt.ts", commonFailure: "N/A — this slot has no single anticipated failure mode by design", validate: "REQUIRED: run_report, last 28 days, dimensions=[eventName] metrics=[eventCount] — real-data only, never a settings field. See \"GA4 deep-analysis slots\" in audit-prompt.ts", severity: "medium" },
  { id: "GA4-D3", title: "Open data-driven finding #3", expectedState: "No fixed expected state — see \"GA4 deep-analysis slots\" in audit-prompt.ts", commonFailure: "N/A — this slot has no single anticipated failure mode by design", validate: "REQUIRED: run_report twice — [7daysAgo,today] and [14daysAgo,8daysAgo], metrics=[sessions,eventCount] — real-data only, never a settings field. See \"GA4 deep-analysis slots\" in audit-prompt.ts", severity: "medium" },
  { id: "GA4-D4", title: "Open data-driven finding #4", expectedState: "No fixed expected state — see \"GA4 deep-analysis slots\" in audit-prompt.ts", commonFailure: "N/A — this slot has no single anticipated failure mode by design", validate: "REQUIRED: run_report, last 28 days, dimensions=[sessionDefaultChannelGroup] metrics=[sessions] — real-data only, never a settings field. See \"GA4 deep-analysis slots\" in audit-prompt.ts", severity: "medium" },
  { id: "GA4-D5", title: "Open data-driven finding #5", expectedState: "No fixed expected state — see \"GA4 deep-analysis slots\" in audit-prompt.ts", commonFailure: "N/A — this slot has no single anticipated failure mode by design", validate: "REQUIRED: run_report, last 28 days, real sessions vs. real key-event completions — real-data only, never a settings field. See \"GA4 deep-analysis slots\" in audit-prompt.ts", severity: "medium" },
  { id: "GA4-D6", title: "Open data-driven finding #6", expectedState: "No fixed expected state — see \"GA4 deep-analysis slots\" in audit-prompt.ts", commonFailure: "N/A — this slot has no single anticipated failure mode by design", validate: "REQUIRED: run_report, last 28 days, metrics=[eventCount,purchaseRevenue,transactions] on the purchase key event — real-data only, never a settings field. See \"GA4 deep-analysis slots\" in audit-prompt.ts", severity: "medium" },
  { id: "GA4-D7", title: "Open data-driven finding #7", expectedState: "No fixed expected state — see \"GA4 deep-analysis slots\" in audit-prompt.ts", commonFailure: "N/A — this slot has no single anticipated failure mode by design", validate: "REQUIRED: run_report, last 28 days, dimensions=[landingPage] metrics=[sessions,conversions], ordered by sessions — real-data only, never a settings field. See \"GA4 deep-analysis slots\" in audit-prompt.ts", severity: "medium" },
  { id: "GA4-D8", title: "Open data-driven finding #8", expectedState: "No fixed expected state — see \"GA4 deep-analysis slots\" in audit-prompt.ts", commonFailure: "N/A — this slot has no single anticipated failure mode by design", validate: "REQUIRED: run_report, last 28 days, dimensions=[country] and separately dimensions=[deviceCategory], metrics=[sessions] — real-data only, never a settings field. See \"GA4 deep-analysis slots\" in audit-prompt.ts", severity: "medium" },
  { id: "GA4-D9", title: "Open data-driven finding #9", expectedState: "No fixed expected state — see \"GA4 deep-analysis slots\" in audit-prompt.ts", commonFailure: "N/A — this slot has no single anticipated failure mode by design", validate: "REQUIRED: run_report, last 28 days, metrics=[sessions,engagedSessions,averageSessionDuration] — real-data only, never a settings field. See \"GA4 deep-analysis slots\" in audit-prompt.ts", severity: "medium" },
  { id: "GA4-D10", title: "Open data-driven finding #10", expectedState: "No fixed expected state — see \"GA4 deep-analysis slots\" in audit-prompt.ts", commonFailure: "N/A — this slot has no single anticipated failure mode by design", validate: "REQUIRED: run_report, last 28 days, a new-vs-returning-user dimension with metrics=[sessions,conversions] — real-data only, never a settings field. See \"GA4 deep-analysis slots\" in audit-prompt.ts", severity: "medium" },
  { id: "GA4-D11", title: "Open data-driven finding #11", expectedState: "No fixed expected state — see \"GA4 deep-analysis slots\" in audit-prompt.ts", commonFailure: "N/A — this slot has no single anticipated failure mode by design", validate: "REQUIRED: run_report, last 28 days, sessions+conversions split paid vs. organic channels — real-data only, never a settings field. See \"GA4 deep-analysis slots\" in audit-prompt.ts", severity: "medium" },
  { id: "GA4-D12", title: "Open data-driven finding #12", expectedState: "No fixed expected state — see \"GA4 deep-analysis slots\" in audit-prompt.ts", commonFailure: "N/A — this slot has no single anticipated failure mode by design", validate: "REQUIRED: list_data_streams cross-checked against the crawl's real detected GA4 measurement ID(s) — real-evidence cross-check only, never a settings field alone. See \"GA4 deep-analysis slots\" in audit-prompt.ts", severity: "medium" },
  { id: "GA4-D13", title: "Open data-driven finding #13", expectedState: "No fixed expected state — see \"GA4 deep-analysis slots\" in audit-prompt.ts", commonFailure: "N/A — this slot has no single anticipated failure mode by design", validate: "REQUIRED: admin_request POST :searchChangeHistoryEvents (v1alpha), a recent real date range — real activity-log only, never a settings field. See \"GA4 deep-analysis slots\" in audit-prompt.ts", severity: "medium" },
  { id: "GA4-D14", title: "Open data-driven finding #14", expectedState: "No fixed expected state — see \"GA4 deep-analysis slots\" in audit-prompt.ts", commonFailure: "N/A — this slot has no single anticipated failure mode by design", validate: "REQUIRED: run_access_report, a recent real date range — real activity-log only, never a settings field. See \"GA4 deep-analysis slots\" in audit-prompt.ts", severity: "medium" },
  { id: "GA4-D15", title: "Open data-driven finding #15", expectedState: "No fixed expected state — see \"GA4 deep-analysis slots\" in audit-prompt.ts", commonFailure: "N/A — this slot has no single anticipated failure mode by design", validate: "OPEN — one more real, data-driven insight from any run_report/run_realtime_report pull, named explicitly — real-data only, never a settings field. See \"GA4 deep-analysis slots\" in audit-prompt.ts", severity: "medium" },

  // ── GA4-1 through GA4-13 (minus GA4-7/9/11/14-25, replaced above): the
  // remaining fixed config-hygiene checks, plus GA4-12/13 which read REAL
  // DATA (run_report results) rather than just a settings toggle — a
  // setting can be "correctly configured" and the real numbers behind it
  // can still be broken, missing, or telling a business story nobody's
  // looking at.
  { id: "GA4-1", title: "Timezone, currency & industry configured sensibly", expectedState: "Property timezone/currency match the business's real market and TLD; industry category is set, not left default", commonFailure: "A property left on US timezone/currency for a GCC business misreports every daily boundary and every revenue figure in the wrong currency", validate: "Call get_property for this property; check timeZone, currencyCode, and industryCategory against what's plausible for the audited domain/business name", severity: "critical" },
  { id: "GA4-2", title: "Data retention window + reset-on-activity", expectedState: "14 months retention with reset-on-activity turned on", commonFailure: "Default 2-month window silently breaks all year-over-year analysis", validate: "Call get_data_retention_settings for this property; check eventDataRetention is FOURTEEN_MONTHS or longer and resetUserDataOnNewActivity is true", severity: "medium" },
  { id: "GA4-3", title: "Enhanced Measurement coverage", expectedState: "Scroll, outbound click, site search, video engagement, file download, and form-interaction sub-toggles all enabled unless there's a documented reason one is off", commonFailure: "Enhanced Measurement left on its narrow default means scroll depth, outbound clicks, and file downloads never get tracked at all — silent blind spots nobody had to build a single GTM tag to close", validate: "Call admin_request GET (v1beta) on this data stream's enhancedMeasurementSettings sub-resource (properties/{id}/dataStreams/{streamId}/enhancedMeasurementSettings) and check which sub-toggles are true/false", severity: "medium" },
  { id: "GA4-4", title: "Google Signals", expectedState: "Enabled", commonFailure: "Off means no Google Ads remarketing audiences and no cross-device reporting at all", validate: "Call admin_request GET (v1beta) on properties/{id}/googleSignalsSettings and check the state field", severity: "medium" },
  { id: "GA4-5", title: "Email/PII redaction", expectedState: "Email redaction turned on for the data stream", commonFailure: "PII bleeds into event payloads — a direct Google ToS violation with real legal exposure", validate: "Call admin_request GET (v1beta) on this data stream's dataRedactionSettings sub-resource and check emailRedactionEnabled", severity: "critical" },
  { id: "GA4-6", title: "URL query parameter redaction", expectedState: "queryParameterRedactionEnabled on, with the site's actual PII-bearing param keys explicitly listed", commonFailure: "The toggle is on but the site's actual parameter names were never added to the list — redaction looks configured but does nothing", validate: "Call admin_request GET (v1beta) on the same dataRedactionSettings sub-resource and check queryParameterRedactionEnabled plus the queryParameterKeys list", severity: "critical" },
  { id: "GA4-8", title: "Attribution model", expectedState: "Data-driven attribution (DDA) active — the only two models that exist since April 2024 are Data-driven and Paid-and-organic last-click", commonFailure: "Last-click misses journeys with 4-50+ touchpoints and carries a Google-channel bias", validate: "Call get_attribution_settings for this property and check reportingAttributionModel", severity: "medium" },
  { id: "GA4-10", title: "Measurement Protocol secret hygiene", expectedState: "Secrets exist only where actually needed, none obviously long-abandoned", commonFailure: "A long-lived, unused Measurement Protocol secret is a standing way for anyone who finds it to spoof server-side hits into the property", validate: "Call list_measurement_protocol_secrets for each data stream and review the list for secrets that look unused or excessive in number", severity: "critical" },
  { id: "GA4-12", title: "Key events marking + real recent volume", expectedState: "Only real business-KPI events marked as key events; every key event's ACTUAL recent event count is non-zero", commonFailure: "Marking page_view or scroll as a conversion destroys conversion-rate validity; a key event with zero real volume in the actual data is a broken conversion nobody noticed", validate: "Call list_key_events, then call run_report with dimensions=[eventName], metrics=[eventCount], dateRanges last 30 days — read the ACTUAL returned counts per key event name, don't just confirm the event is marked", severity: "critical" },
  { id: "GA4-13", title: "Custom dimensions/metrics registered AND populated with real values", expectedState: "A sample run_report pull on each registered custom dimension/metric returns real, varied values — not blank/'(not set)' rows", commonFailure: "A custom dimension gets created once and the underlying GTM/site parameter is never actually wired to populate it — registered but permanently empty in the real data", validate: "Call list_custom_dimensions/list_custom_metrics, then run_report using those exact dimension/metric API names over the last 30 days — read the actual rows returned, flag any dimension that comes back entirely '(not set)'", severity: "medium" },
];

// Standardized against "GTM Container Audit Checklist: Top 25 High-Impact
// Checks" (prepared by Gemini Notebook) — the business-facing methodology
// document the agency actually audits against. Every point below keeps that
// doc's title/intent verbatim, but `validate` is rewritten against what this
// worker can ACTUALLY call (same discipline as this file's own top-of-file
// doc comment): no GTM Preview/DebugView web UI, no third-party crawler
// (Screaming Frog/ObservePoint), no live conversation with the marketing
// team — only the GTM API's tags/triggers/variables/built-in-variables/
// versions resources, the static crawl signal, this run's PageSpeed sweep,
// and — only when GA4 is ALSO connected this run — a GA4 Data API
// cross-check. Order and numbering (GTM-1..GTM-25) follows the source doc's
// own five sections (Installation, Data Quality, Hygiene, Consent/Privacy,
// Advanced) exactly.
export const GTM_CHECKLIST: ChecklistPoint[] = [
  // I. Installation & Structural Integrity
  //
  // Not from the source doc's own "Tag Snippet Presence & Location" item —
  // that one only tests something homepage-only crawl access can already
  // all-but-guarantee passes once GTM is confirmed connected at all (the
  // original install is rarely touched again), so it added a critical slot
  // with near-zero real chance of catching anything. Replaced with a
  // distinct, extremely common real-world failure that IS checkable from
  // this worker's actual GTM API access and genuinely fails often: a GA4
  // Configuration tag's default auto-pageview (sendPageView) left on
  // alongside a separate manual GA4 Event tag also sending page_view — a
  // subtle default-behavior trap most non-expert setups fall into,
  // precisely because it isn't obvious the config tag already covers it.
  // crawl.structuralSignals.gtmScriptEarlyInHead/gtmNoscriptRightAfterBody
  // still exist (computed in crawl.ts, surfaced in the prompt) as
  // unscored informational context, just no longer a scored checklist item.
  { id: "GTM-1", title: "Duplicate page_view firing (auto-pageview + manual event tag)", expectedState: "Either the GA4 Configuration tag's sendPageView is left on with no separate manual page_view Event tag also configured, or sendPageView is deliberately disabled if a manual tag exists — never both firing at once", commonFailure: "A manual page_view Event tag added alongside the config tag's default auto-pageview double-counts every single pageview — inflates sessions, deflates bounce rate, and skews every landing-page/funnel report built on top of it", validate: "Call get_tag on the GA4 Configuration tag and check its sendPageView field (true unless explicitly disabled); call list_tags/get_tag for any GA4 Event tag configured with event name page_view; flag if both are active simultaneously", severity: "critical" },
  { id: "GTM-2", title: "Elimination of duplicate GA4 Configuration/Google tags", expectedState: "Exactly one active GA4 Configuration/Google Tag fires from this container, with no second copy firing from outside GTM (a CMS plugin, a hardcoded script)", commonFailure: "A duplicate GA4 tracking method inflates every session count, drops reported bounce rate, and roughly halves the real conversion rate", validate: "Call list_tags for the workspace, filter to GA4 Configuration/Google Tag type, and flag more than one active (unpaused) instance; cross-reference the crawl's detected script signal for a second gtag.js/GA4 snippet running outside this container entirely", severity: "critical" },
  { id: "GTM-3", title: "Measurement ID & container-wide constant standardization", expectedState: "The GA4 Measurement ID and ad-platform pixel/conversion IDs are set once as GTM Constant variables and referenced by every tag that needs them — not retyped inline on each tag", commonFailure: "Hardcoding the same ID across many individual tags makes environment moves (test → live) error-prone — a missed hardcoded copy can route production data at a test property/account", validate: "Call list_variables for the workspace and check for user-defined Constant-type variables covering the GA4 Measurement ID and any ad-platform IDs; call get_tag on the GA4/ad tags and confirm they reference those variables rather than a literal ID string", severity: "medium" },
  { id: "GTM-4", title: "Trigger URL pattern and slug validation", expectedState: "Every trigger with a Page URL/Page Path condition matches a path that's actually live on the site today — not a stale permalink from before a migration or CMS change", commonFailure: "A silently stale URL condition (e.g. /shop/checkout/ after the live path moved to /checkout/) breaks the trigger with no visible error — the tag just quietly stops firing", validate: "Call list_triggers for the workspace, then get_trigger on any with a Page URL/Page Path filter, and check each condition's value against the real page URLs the site-wide PageSpeed sweep actually discovered and crawled this run", severity: "critical" },
  { id: "GTM-5", title: "Activation of required pre-built variables", expectedState: "The core built-in variable groups are enabled: Click (Element/Classes/URL/ID), Page (URL/Path/Hostname/Referrer), Form (Element/ID/Classes/Text/URL), and History, at minimum", commonFailure: "A trigger built against a built-in variable that was never switched on has nothing to read — it silently fails to fire as designed, with no error surfaced anywhere", validate: "Call list_built_in_variables for the workspace and check that the essential Click/Page/Form/History groups are actually enabled, not left on GTM's disabled-by-default state", severity: "medium" },

  // II. Data Quality & Event Precision
  { id: "GTM-6", title: "DataLayer-driven conversion triggers (no URL-based conversion tags)", expectedState: "The primary purchase/conversion tag's trigger is a Custom Event mapped to a specific dataLayer push (e.g. event: 'purchase'), not a Page URL trigger on a thank-you/confirmation path", commonFailure: "A URL-triggered conversion tag fires again on every refresh, back-button return, or reopened tab on that page — silently double- and triple-counting the same conversion", validate: "Call list_triggers and get_tag on the primary conversion/purchase tag; confirm its firingTriggerId resolves to a customEvent-type trigger tied to a dataLayer event name, not a pageUrl-type condition on a confirmation path", severity: "critical" },
  { id: "GTM-7", title: "Event-level transaction ID deduplication", expectedState: "The purchase tag's parameters include transaction_id (or an equivalent event_id) mapped from a real, unique per-order dataLayer value", commonFailure: "Without a unique ID, the same conversion counted from both the web pixel and any server-side hit can't be deduplicated by the platform, inflating reported ROAS", validate: "Call get_tag on the purchase/conversion tag(s) and check the parameter list for a transaction_id/event_id field mapped to a Data Layer Variable, not a blank or hardcoded value", severity: "critical" },
  { id: "GTM-8", title: "Required parameter completeness for GA4 recommended events", expectedState: "purchase/begin_checkout/add_to_cart/generate_lead (and similar recommended events) map currency and value (plus items where applicable) to real, non-empty Data Layer Variables — not left blank", commonFailure: "A recommended event fired without its required parameters gets treated by GA4 as an unrecognized custom event — it stops feeding standard reporting and any catalog/audience matching that depends on it", validate: "Call get_tag on each GA4 Event tag matching a recommended event name and check its parameter list for currency/value (and items for ecommerce events) mapped to non-empty Data Layer Variables", severity: "critical" },
  { id: "GTM-9", title: "Validation of reserved event and parameter names", expectedState: "Custom GA4 Event tags use event/parameter names outside Google's reserved list (session_start, first_visit, user_id, etc. are never repurposed for a custom send)", commonFailure: "GA4 silently discards an event payload that collides with a reserved automatically-tracked name — the tag looks like it fired but nothing usable lands in reports", validate: "Call list_tags and get_tag on every GA4 Event tag; cross-reference each configured event name and parameter key against GA4's published reserved-name list", severity: "medium" },
  { id: "GTM-10", title: "Single Page Application (SPA) virtual pageview setup", expectedState: "A History Change-type trigger (or an equivalent custom-event virtual-pageview push) drives page view tracking wherever the site behaves like an SPA", commonFailure: "A default Page View trigger only fires once on the initial document load — every subsequent client-side route change goes untracked, understating sessions and breaking funnel analysis", validate: "Call list_triggers for the workspace and check for a historyChange-type trigger; cross-reference against crawl.structuralSignals.looksLikeSpaShell (a real, deterministic proxy computed from the homepage's stripped body text — treat it as a signal to weigh, not a confirmed SPA)", severity: "medium" },
  { id: "GTM-11", title: "DataLayer variable schema match", expectedState: "Each Data Layer Variable's configured path (e.g. ecommerce.items.0.item_name) matches the real, current nested structure the site's own dataLayer.push calls use — not a stale or guessed path", commonFailure: "A site/plugin update that renames or restructures dataLayer keys leaves the GTM variable silently resolving to undefined everywhere it's referenced, with nothing flagging why", validate: "Call list_variables for the workspace, then get_variable on each Data Layer Variable (type 'v'), and check its configured path is a plausible, well-formed dot-notation reference consistent with GA4's Enhanced Ecommerce schema; cross-reference against crawl.structuralSignals.cmsPlatformGuess (a real fingerprint match on the raw source, null if none of the recognized platforms matched) for whether the path looks consistent with that platform's typical dataLayer shape", severity: "critical" },

  // III. Container Hygiene & Speed Optimization
  { id: "GTM-12", title: "Pruning of dead/stale tags from past campaigns", expectedState: "Every active (unpaused) tag maps to a currently relevant platform/campaign — nothing left running from a tool or promotion nobody's monitoring any more", commonFailure: "A container carrying legacy pixels (expired campaigns, a long-abandoned analytics tool) loads that dead weight on every single pageview, quietly hurting load speed for no benefit", validate: "Call list_tags for the workspace and review the full active-tag list for any tag whose platform/name suggests a tool or campaign that's no longer plausibly in use", severity: "medium" },
  { id: "GTM-13", title: "Transitioning Custom HTML tags to Sandbox Gallery templates", expectedState: "Tags for common platforms (Meta Pixel, TikTok, Clarity, etc.) use an official/community Template Gallery tag type rather than a hand-pasted Custom HTML tag, wherever a native template exists for that platform", commonFailure: "A raw Custom HTML tag runs unsandboxed JavaScript directly in the page — no vendor auto-updates, higher risk of layout shift/script conflicts, and friction against a strict Content-Security-Policy", validate: "Call list_tags for the workspace and tally tags with type 'html'; for each, read its html parameter (via get_tag) to identify the platform it's pasting in, and flag ones with a well-known native GTM template available instead", severity: "medium" },
  { id: "GTM-14", title: "Offloading core visual & functional site elements", expectedState: "Every tag in the container is a measurement/analytics/advertising script — no cookie-consent banner, hero content, or functional UI widget is being injected through a GTM tag", commonFailure: "GTM tags load asynchronously after the page itself, so using one to render a visual/functional element delays that content's appearance — directly hurting LCP/CLS and Core Web Vitals", validate: "Call get_tag on every Custom HTML tag and read its source for DOM-injecting UI code (a consent banner, a popup, hero markup); cross-reference against this run's own PageSpeed sweep CWV data (LCP/CLS) for a plausible correlation", severity: "medium" },
  { id: "GTM-15", title: "Variable consolidation via Lookup and RegEx Tables", expectedState: "Where several tags differ only by a condition like domain, currency, or account ID, a Lookup Table or RegEx Table variable consolidates them into one tag instead of a separate hand-copied tag per condition", commonFailure: "Bloating the container with near-identical tags (one per subdomain/currency/ad account) makes it harder to maintain and raises the odds one copy silently drifts out of sync with the others", validate: "Call list_variables for the workspace and check for Lookup Table or RegEx Table variables; call list_tags to check whether visibly near-duplicate tags exist that a lookup/regex variable could consolidate instead", severity: "low" },

  // IV. Privacy, Consent Mode v2, and GDPR Compliance
  { id: "GTM-16", title: "Script execution sequencing (consent defaults must load first)", expectedState: "The page source initializes gtag('consent','default',...) (or the CMP's equivalent default-consent call) physically before the GTM container snippet loads", commonFailure: "If GTM loads and starts firing tags before consent defaults are set, tags run with full tracking privileges regardless of the visitor's actual choice — a direct compliance violation (GDPR/DMA)", validate: "Check crawl.structuralSignals.consentDefaultBeforeGtm — computed directly from the raw page source's real script order; null means no consent-default call was found at all (a separate, distinct problem from finding one that fires too late)", severity: "critical" },
  { id: "GTM-17", title: "Proper CMP trigger assignment", expectedState: "The tag that initializes the CMP/consent banner is assigned to GTM's built-in 'Consent Initialization - All Pages' trigger type, not a generic Page View/Initialization trigger", commonFailure: "Assigning CMP init to a generic trigger risks tracking tags firing in the same load cycle before the visitor's consent choice is actually registered", validate: "Call list_triggers for the workspace and check for a consentInitialization-type trigger; call get_tag on the CMP/consent-related tag and confirm its firingTriggerId points to that trigger type", severity: "critical" },
  { id: "GTM-18", title: "Tag behavior under denial of consent", expectedState: "Every advertising/remarketing tag's consentSettings field is deliberately set (NEEDED, tied to the correct consent type) so it's blocked when that consent type is denied — not left at the default NOT_SET, which ignores denial entirely", commonFailure: "A tag left on consentSettings NOT_SET fires regardless of what the visitor actually chose — the single most common real-world Consent Mode compliance gap", validate: "Call get_tag on every tag in the workspace and check its consentSettings.consentStatus field for NEEDED (mapped to the right consent type) rather than the default NOT_SET", severity: "critical" },
  { id: "GTM-19", title: "Client-side PII redaction", expectedState: "GA4's own email/URL-query-parameter redaction is relied on where GA4 is connected, and/or a Custom JavaScript variable actively scrubs PII patterns (email, phone) from page_location/query-string values before any tag reads them", commonFailure: "PII landing in a URL parameter (e.g. a newsletter signup's ?email=... query string) or a custom tag parameter is a direct Google ToS violation with real risk of property suspension", validate: "Call list_variables for the workspace and check for a Custom JavaScript variable that scrubs PII patterns from page_location-derived values; when GA4 is also connected this run, treat GA4-5/GA4-6's own redaction settings as the primary safeguard instead of expecting GTM to duplicate that logic", severity: "critical" },

  // V. Advanced & Performance Optimization
  { id: "GTM-20", title: "Filtering of admin and internal developer traffic", expectedState: "At least one trigger's filter conditions exclude sessions carrying an internal/admin/staff signal (a specific cookie, user property, or IP-based variable) from firing production analytics tags", commonFailure: "With no such exclusion anywhere in the container, every internal team, agency, or CMS-editing session keeps polluting real visitor/conversion metrics indefinitely", validate: "Call list_triggers for the workspace, then get_trigger on candidates, and check filter conditions for anything referencing an internal/admin/staff cookie, variable, or IP signal", severity: "medium" },
  { id: "GTM-21", title: "GTM metadata custom dimensions", expectedState: "GTM Container ID and/or version metadata is mapped as a parameter/user property on the Google Tag/GA4 Configuration tag, so it lands in GA4 as an identifiable custom dimension", commonFailure: "Without this, tracing a data-quality issue back to the exact GTM tag/version that produced it is far slower — every event looks the same regardless of which tag actually sent it", validate: "Call get_tag on the Google Tag/GA4 Configuration tag and check its parameter list for a container ID/version field mapped from a built-in variable ({{Container ID}}/{{Container Version}})", severity: "low" },
  { id: "GTM-22", title: "User property mapping of click-based ad IDs (GCLID/MSCLKID)", expectedState: "The Google Tag/GA4 Configuration tag maps gclid and msclkid (at minimum) as user properties, sourced from URL query parameters or a first-party cookie capturing them", commonFailure: "Without this, click-attribution parameters aren't preserved at the user level — offline conversion imports and CRM-based matching lose the ability to tie a closed deal back to the ad click that drove it", validate: "Call get_tag on the Google Tag/GA4 Configuration tag and check its user-properties/fields-to-set list for gclid/msclkid mapped from a URL query variable or cookie variable", severity: "medium" },
  { id: "GTM-23", title: "DataLayer login status and User-ID capturing", expectedState: "A dataLayer event (e.g. user_login) fires on authentication carrying login_status and a hashed, non-PII user_id, with a corresponding tag/variable wired to read it and set GA4's User-ID", commonFailure: "Without a consistent User-ID passed to GA4, cross-device journeys (browse on mobile, buy on desktop) can't be stitched into one user's real path — attribution silently underperforms", validate: "Call list_variables for a Data Layer Variable reading user_id/login_status, and get_tag on the GA4 Configuration tag to confirm it maps that variable to GA4's User-ID field", severity: "medium" },
  { id: "GTM-24", title: "Client-ID and Session-ID variable extraction", expectedState: "A Custom JavaScript or Cookie variable successfully extracts the live GA4 client_id (from the _ga cookie or the GA4 API object) and session_id, ready to pass to a backend/CRM for Measurement Protocol offline-conversion import", commonFailure: "Without capturing these, offline conversions (a CRM lead that later closes) can't be stitched back to the original web session via the Measurement Protocol — that revenue path stays invisible to GA4 entirely", validate: "Call list_variables for the workspace and check for a Custom JavaScript or First-Party Cookie variable configured to read the _ga cookie/client_id and a session identifier", severity: "low" },
  { id: "GTM-25", title: "Behavioral validation & session replay target handshakes", expectedState: "Where a session-replay tool (Microsoft Clarity, Hotjar, etc.) is present, custom tags forward key events (add_to_cart, coupon usage, form errors) to it as custom events/tags — not just to GA4/ad platforms", commonFailure: "Without this handshake, recordings can't be filtered by the moments that actually matter (an abandoned checkout, a form error) — the tool ends up rarely used for the analysis it's meant for", validate: "Call list_tags for the workspace and check whether a Clarity/Hotjar tag exists alongside the conversion-tracking tags, and whether its trigger set overlaps with the same custom events (add_to_cart, checkout, form errors) the GA4/ad tags use", severity: "low" },
];

export const WEBSITE_CHECKLIST: ChecklistPoint[] = [
  { id: "WEB-1", title: "Container/tag deployment reaches production", expectedState: "Any detected tracking snippet is real, present in the live page source", commonFailure: "A tag exists in the platform's config but was never actually deployed to the live site", validate: "Check the raw page-source crawl for the actual snippet, not just what the platform's own config claims", severity: "critical" }, // 2.1
  { id: "WEB-2", title: "dataLayer declared before the tag snippet", expectedState: "dataLayer array declared above the GTM container script in page source", commonFailure: "Pushes that fire before declaration are silently lost", validate: "Check page-source ordering: dataLayer declaration before the GTM script tag", severity: "medium" }, // 3.8
  { id: "WEB-3", title: "Consent banner wired to tracking", expectedState: "A consent mechanism visibly gates tracking scripts, not just a cookie notice", commonFailure: "A banner exists but tracking fires regardless of the visitor's choice", validate: "Check the crawl signal for a consent-related script, cross-referenced against whether tracking scripts appear unconditionally in source", severity: "critical" }, // 4.1
  { id: "WEB-4", title: "Legacy Universal Analytics script removed", expectedState: "No leftover analytics.js/ga('create'...) calls from the old GA product", commonFailure: "Dead legacy script adds page weight and blocking JS, directly hurting load speed and SEO signals", validate: "Grep the raw page source for analytics.js or ga('create'...) calls", severity: "medium" }, // 1.25
  { id: "WEB-5", title: "PII leaking into URLs", expectedState: "Forms submit via POST, not GET — no PII visible in the URL bar", commonFailure: "GET-submitted forms leak email/name into page_location, and into every analytics tool watching URLs", validate: "Check forms in the crawled source for GET vs POST method", severity: "critical" }, // 4.5
  { id: "WEB-6", title: "UTM parameters survive redirects", expectedState: "Campaign parameters intact after any www/https/trailing-slash redirect", commonFailure: "A redirect rule silently strips the query string, killing attribution for those landing pages", validate: "Follow a UTM-tagged URL through any redirect and confirm the query string survives", severity: "critical" }, // 5.3
  { id: "WEB-7", title: "Internal links don't carry UTM parameters", expectedState: "No internal navigation link is tagged with utm_* parameters", commonFailure: "An internal link re-attributes the visitor's whole session away from their real original source", validate: "Scan internal navigation links in the crawled source for utm_* parameters", severity: "medium" }, // 5.5
  { id: "WEB-8", title: "Page load speed vs tag-firing reliability", expectedState: "Tracking requests complete early enough in the load that a visitor who bounces quickly is still counted — on the conversion-path pages, not just the homepage", commonFailure: "A slow page means visitors leave before tracking scripts even finish loading — silent data loss; a fast homepage can still hide a slow checkout/product page", validate: "Live browser — read the page's own PerformanceNavigationTiming (domContentLoaded/load) and compare against when the tracking requests actually resolved in the network list; repeat on one discovered product/cart page, not only the homepage — only evaluable when browser access is granted this run", severity: "critical" }, // 8.11
  { id: "WEB-13", title: "Core Web Vitals health", expectedState: "Largest Contentful Paint and Cumulative Layout Shift within Google's 'Good' thresholds (LCP under 2.5s, CLS under 0.1) on the pages checked", commonFailure: "Poor Core Web Vitals directly hurt conversion rate and organic search ranking, and layout shift specifically moves a CTA out from under a visitor's finger mid-tap", validate: "Live browser — measure LCP and CLS in-page via a PerformanceObserver on the 'largest-contentful-paint' and 'layout-shift' entry types (a real measurement from this load, not a lab estimate), on the homepage plus one discovered conversion-path page — only evaluable when browser access is granted this run", severity: "critical" },
  { id: "WEB-14", title: "Mobile viewport rendering and tap-target problems", expectedState: "At a real mobile viewport the page renders without horizontal overflow, and the primary CTAs stay visible and large enough to tap (~44px)", commonFailure: "A desktop-first layout that overflows or shrinks its buttons on mobile penalizes the majority-mobile GCC audience at exactly the moment they'd convert — invisible to anyone testing on a laptop", validate: "Live browser — resize/emulate a mobile viewport (~390x844), then check document.scrollWidth against the viewport width for horizontal overflow and measure the primary CTA's rendered box — only evaluable when browser access is granted this run", severity: "medium" },
  // WEB-15 through WEB-17 are only evaluable with real browser access (the
  // chrome-devtools MCP tool, granted when the visitor selected no
  // GA4/GTM tool to audit instead — see audit-prompt.ts). Everything else
  // in this checklist works from a static HTML fetch; these three need
  // something to actually execute.
  { id: "WEB-15", title: "Console errors on page load", expectedState: "No JavaScript errors during load or a brief idle period", commonFailure: "A broken script silently corrupts tracking, checkout, or UI behavior, and most owners never open DevTools to notice", validate: "Live browser console messages, only evaluable when browser access is granted this run", severity: "critical" },
  { id: "WEB-16", title: "Tags configured actually fire", expectedState: "Every tracking snippet visible in page source is confirmed firing a real network request at runtime", commonFailure: "A tag looks correctly installed in the source but never fires live — wrong trigger, blocked by an ad blocker/CSP, or an unpublished container — completely invisible without checking the live network tab", validate: "Live browser network requests, only evaluable when browser access is granted this run", severity: "critical" },
  { id: "WEB-17", title: "Duplicate tag firing at runtime", expectedState: "Each tracking pixel fires exactly once per relevant event", commonFailure: "The same tag firing twice (a leftover hardcoded snippet plus a GTM copy, or two tags on overlapping triggers) inflates every conversion and engagement metric it feeds", validate: "Live browser network requests, checked for repeat fires on the same event — only evaluable when browser access is granted this run", severity: "critical" },

  // WEB-18 onward back the "visitor gave us no GA4/GTM access" route (see
  // the free-audit form's "None of these" option) — deeper
  // console/network/DOM/security/SEO/accessibility coverage than a plain
  // tracking audit needs, so a "none" run still comes back substantive
  // instead of two thin categories. Grouped by what actually backs each
  // one: console/runtime, network, security, SEO, accessibility, tag
  // hygiene, e-commerce code health, resource weight. Every point is backed
  // by either the static crawl or the headless browser — the Lighthouse
  // audit ids several of these used to cite are gone along with the
  // PageSpeed category (2026-09-09), replaced by the equivalent browser/DOM
  // check; anything marked "only evaluable when browser access is granted"
  // needs the chrome-devtools MCP tool.

  // Console & JS runtime health
  { id: "WEB-18", title: "Unhandled promise rejections / async errors", expectedState: "No unhandled promise rejections during load or a brief idle/interaction period", commonFailure: "An async bug silently breaks checkout/cart state updates without ever throwing a visible page error", validate: "Live browser console messages, watched during a brief idle period after load — only evaluable when browser access is granted this run", severity: "medium" },
  { id: "WEB-21", title: "Repeated/looping console errors", expectedState: "No error repeats more than a handful of times during a normal page-load-plus-idle window", commonFailure: "A render loop or bad polling interval spams the same error dozens of times a second — a distinct failure mode from a one-off bug, usually a bigger performance problem too", validate: "Live browser console messages, counted by distinct message during a fixed observation window — only evaluable when browser access is granted this run", severity: "medium" },
  { id: "WEB-22", title: "Mixed-content warnings in console", expectedState: "No HTTP resource loaded from an HTTPS page", commonFailure: "Browsers block or warn on mixed content, and it undermines the padlock/trust signal a checkout page depends on", validate: "Live browser console messages for mixed-content warnings — only evaluable when browser access is granted this run", severity: "critical" },

  // Network, tags & resource loading
  { id: "WEB-23", title: "Broken resource requests", expectedState: "No first-party static asset request returns 404 during page load", commonFailure: "A renamed/deleted asset still referenced in code or a stylesheet silently breaks styling or functionality with no visible error to a casual visitor", validate: "Live browser network requests, filtered to 4xx/5xx responses on first-party asset URLs — only evaluable when browser access is granted this run", severity: "medium" },
  { id: "WEB-24", title: "Undisclosed third-party trackers found firing", expectedState: "No tracking pixel fires that the visitor didn't disclose selecting (GA4/GTM) — or if one does, it's flagged, not silently ignored", commonFailure: "A Meta/TikTok/Snapchat Pixel, Hotjar, or Clarity snippet is live and firing even though the visitor said they have none of the tools this audit asks about — a real signal their self-report was incomplete, worth surfacing regardless", validate: "Live browser network requests, matched against known tracker request patterns (facebook.com/tr, analytics.tiktok.com, hotjar.com, clarity.ms) — only evaluable when browser access is granted this run", severity: "medium" },
  { id: "WEB-26", title: "Slow/hanging network requests blocking meaningful content", expectedState: "No request in the critical rendering path takes more than ~3s to resolve", commonFailure: "A slow third-party call blocks visible content from ever appearing, even if the site's own code is fast", validate: "Live browser network requests, filtered by request duration — only evaluable when browser access is granted this run", severity: "critical" },
  { id: "WEB-27", title: "Mixed content at the network-request level", expectedState: "No HTTP request actually attempted from an HTTPS page (not just a console warning about it)", commonFailure: "A blocked mixed-content request silently drops a resource the page needed, with no visible error unless the network panel is checked directly", validate: "Live browser network requests, filtered for blocked/insecure requests — only evaluable when browser access is granted this run", severity: "critical" },

  // Security basics
  { id: "WEB-28", title: "HTTPS not enforced sitewide", expectedState: "Every page redirects HTTP to HTTPS; no HTTP-accessible fallback left reachable", commonFailure: "An HTTP variant left reachable undermines the HTTPS the rest of the site relies on for trust and for tools requiring secure context", validate: "The crawl's own response (was the http:// URL redirected to https, or served as-is), confirmed in the live browser by navigating the plain-http variant of the homepage and one inner page — only fully evaluable when browser access is granted this run", severity: "critical" },
  { id: "WEB-29", title: "Missing security headers", expectedState: "Content-Security-Policy, X-Content-Type-Options, Referrer-Policy, and Strict-Transport-Security all present", commonFailure: "Missing headers leave the site more exposed to XSS, MIME-sniffing, and referrer-leak classes of issues than a one-line header config would prevent", validate: "The crawl's captured response headers — a header's absence from that object means it genuinely wasn't sent", severity: "medium" },
  { id: "WEB-30", title: "Exposed production source maps", expectedState: "No `.js.map` files reachable in production", commonFailure: "A `.js.map` file left publicly fetchable hands anyone the full unminified source of the app, including any secrets or business logic that shouldn't be public", validate: "Live browser network requests during page load for any `.map` file request — only evaluable when browser access is granted this run", severity: "medium" },
  { id: "WEB-31", title: "Exposed config/leftover files", expectedState: "No `.env`, `.git/config`, or backup file reachable at a guessable path", commonFailure: "A leftover config or version-control file exposes credentials or internal structure to anyone who thinks to check", validate: "Live browser — navigate directly to a small set of common leak paths (/.env, /.git/config) and confirm each returns a real 404, not a 200 — only evaluable when browser access is granted this run", severity: "critical" },
  { id: "WEB-32", title: "Outdated/vulnerable JS library versions in use", expectedState: "No known-vulnerable JS library version detected", commonFailure: "An old library version with a known CVE stays in production indefinitely because nobody's watching for it", validate: "Live browser — read the version off each library that exposes one on window (jQuery.fn.jquery, Vue.version, React.version, bootstrap's own global, etc.) and cross-check the crawl's script src URLs for a pinned version in the filename/path; flag any version publicly known to carry a CVE — only fully evaluable when browser access is granted this run", severity: "critical" },
  { id: "WEB-33", title: "Missing clickjacking protection", expectedState: "X-Frame-Options or a CSP frame-ancestors directive present", commonFailure: "Without it, the site can be iframed onto a malicious page and tricked into accepting clicks meant for something else — a real, well-known attack class this one header fully closes off", validate: "The crawl's captured response headers, specifically x-frame-options and content-security-policy's frame-ancestors directive", severity: "medium" },
  { id: "WEB-34", title: "First-party cookies missing security flags", expectedState: "Secure, HttpOnly, and SameSite flags set on first-party cookies where appropriate", commonFailure: "A session cookie missing HttpOnly is readable by any injected script; missing Secure means it can leak over a plain HTTP request", validate: "Live browser Application/cookie inspection, plus the crawl's own set-cookie header where present — only fully evaluable when browser access is granted this run", severity: "medium" },

  // SEO fundamentals
  { id: "WEB-35", title: "Meta description missing/wrong length/duplicated", expectedState: "A unique, appropriately-length meta description on key pages", commonFailure: "Missing or duplicated descriptions mean Google writes its own snippet instead — a real, avoidable loss of control over how the listing reads in search results", validate: "The crawl's own <meta name=description> tag — present, roughly 50-160 characters, and not the same text as another checked page's", severity: "medium" },
  { id: "WEB-36", title: "Title tag missing/wrong length/duplicated", expectedState: "A unique, appropriately-length <title> per page", commonFailure: "A missing or duplicated title tag directly hurts both click-through rate in search results and keyword relevance signal", validate: "The crawl's own <title> tag — present, roughly 30-60 characters, and not duplicated across the checked pages", severity: "medium" },
  { id: "WEB-37", title: "Canonical tag missing or pointing somewhere wrong", expectedState: "A correct self-referencing (or intentionally cross-referencing) canonical tag on every indexable page", commonFailure: "A missing or wrong canonical splits ranking signal across URL variants, or accidentally tells Google to index the wrong page entirely", validate: "The crawl's own <link rel=canonical> tag — present, absolute, same-origin, and pointing at the page itself unless there's a clear reason not to", severity: "critical" },
  { id: "WEB-38", title: "robots.txt missing, invalid, or blocking the whole site", expectedState: "A valid robots.txt exists and doesn't accidentally disallow the pages meant to rank", commonFailure: "A leftover 'Disallow: /' from a staging environment migration silently deindexes the entire live site — one of the single most damaging, easy-to-miss SEO mistakes", validate: "Live browser — navigate to /robots.txt directly and read its real content, checking for a blanket 'Disallow: /' or a Disallow covering the money pages; also check the crawl's own meta robots tag and X-Robots-Tag header for a site-wide noindex", severity: "critical" },
  { id: "WEB-40", title: "Missing structured data for key page types", expectedState: "Product/Organization/BreadcrumbList schema.org markup present where applicable", commonFailure: "Missing structured data forfeits rich-result eligibility (star ratings, price, breadcrumbs in search results) that directly affects click-through rate", validate: "The crawl's page source — parse every <script type=\"application/ld+json\"> block (plus any microdata itemtype attributes) and check which schema.org types are actually declared for this page type", severity: "medium" },
  { id: "WEB-41", title: "Missing Open Graph/Twitter Card tags", expectedState: "og:title/og:description/og:image and Twitter Card equivalents present", commonFailure: "A shared or paid-social link renders as a bare URL with no image/preview — directly hurts click-through on every paid social placement, a real ad-spend efficiency issue for this audience specifically", validate: "Static crawl signal — check page source for og:*/twitter:* meta tags directly", severity: "medium" },
  { id: "WEB-42", title: "Money pages accidentally noindex/nofollow'd", expectedState: "No revenue-critical page (product, category, home) carries a noindex or nofollow directive it shouldn't", commonFailure: "A noindex meant for a staging environment or a low-value filter page accidentally ships on a real product page — pages that should rank become invisible to search entirely", validate: "Static crawl signal — check page source meta robots tag and the X-Robots-Tag response header", severity: "critical" },

  // Accessibility
  { id: "WEB-43", title: "Color contrast fails WCAG AA", expectedState: "Text/background color contrast meets WCAG AA minimums", commonFailure: "Low-contrast text is unreadable for a meaningful share of visitors, and is also a common legal-exposure area (accessibility lawsuits) in some markets", validate: "Live browser — sample the computed color/background-color of the main body copy, nav links, and primary CTA, compute the WCAG contrast ratio, and flag anything under 4.5:1 (3:1 for large text) — only evaluable when browser access is granted this run", severity: "medium" },
  { id: "WEB-44", title: "Images missing alt text", expectedState: "Every meaningful image has descriptive alt text", commonFailure: "Screen-reader users get nothing from the image, and search engines lose an image-SEO signal too", validate: "The crawl's page source — count <img> tags with no alt attribute at all (an empty alt=\"\" on a purely decorative image is correct, a missing attribute is not); confirm in the live browser for images the site injects client-side", severity: "medium" },
  { id: "WEB-45", title: "Form inputs missing associated labels", expectedState: "Every form input has a properly associated <label>", commonFailure: "An unlabeled checkout/contact form field is confusing or unusable for assistive-technology users at exactly the point of conversion", validate: "Live browser DOM — for every input/select/textarea, check for an associated <label for>, a wrapping label, or an aria-label/aria-labelledby; a placeholder alone does not count — only fully evaluable when browser access is granted this run", severity: "critical" },
  { id: "WEB-46", title: "Buttons/links missing accessible names", expectedState: "Every interactive button/link has a real accessible name, not just an icon with nothing else", commonFailure: "An icon-only 'add to cart' button with no accessible name is literally unusable via screen reader — a direct conversion-path accessibility failure", validate: "Live browser DOM — for every button and anchor, check that it resolves to a non-empty accessible name (text content, aria-label, aria-labelledby, or an inner image's alt) — only fully evaluable when browser access is granted this run", severity: "medium" },
  { id: "WEB-49", title: "Missing/wrong lang attribute", expectedState: "The page's <html lang> attribute is present and correct — critical for bilingual AR/EN GCC sites specifically", commonFailure: "A missing or incorrect lang attribute (e.g. declaring 'en' on an Arabic page) breaks assistive tech pronunciation switching and confuses search engines about which regional/language audience the page targets", validate: "The crawl's page source — the <html lang> attribute is present, a valid BCP-47 value, and actually matches the language the page's own copy is written in (check dir=\"rtl\" too on an Arabic page)", severity: "medium" },

  // Tag hygiene & trust signals without account access
  { id: "WEB-50", title: "No consent signal reaching any script despite a cookie banner existing", expectedState: "A visible consent banner's choice actually changes what scripts run/fire", commonFailure: "A banner exists purely for legal cover, but every script behind it fires regardless of the visitor's actual choice — undermines both compliance and visitor trust", validate: "Live browser — accept vs decline the banner and compare network requests before/after — only evaluable when browser access is granted this run", severity: "critical" },
  // E-commerce / conversion-path code health
  { id: "WEB-54", title: "Cart/checkout page throws console errors or fails to load", expectedState: "The cart/checkout page (when one was discovered) loads cleanly with no console errors", commonFailure: "A JS error specifically on the highest-intent page in the entire funnel silently costs revenue with nobody noticing until someone checks manually", validate: "Live browser — navigate specifically to any cart/checkout-looking URL from the discovered-pages list and repeat the console-error check there — only evaluable when browser access is granted this run", severity: "critical" },
  { id: "WEB-55", title: "Missing Product schema (price/availability)", expectedState: "Product pages carry schema.org Product markup with price and availability", commonFailure: "Missing product schema forfeits Google Shopping/rich-result eligibility — a direct, measurable revenue channel this specifically blocks", validate: "Live browser — navigate to a product URL from the discovered-pages list and read its rendered page source for schema.org Product/Offer markup (price and availability specifically)", severity: "medium" },
  { id: "WEB-56", title: "Primary Add-to-Cart/checkout CTA missing, hidden, or disabled", expectedState: "The primary conversion CTA is present, visible, and not disabled on a product/cart page", commonFailure: "A CTA accidentally left disabled or hidden by a CSS/deploy bug silently blocks every conversion from that page until someone notices — the single most expensive class of bug this audit can catch", validate: "Live browser DOM inspection of a product/cart page from the discovered-pages list, confirming the primary CTA element exists, is visible, and isn't disabled — only evaluable when browser access is granted this run", severity: "critical" },

  // Ecommerce dataLayer implementation — evaluable purely from what the SITE
  // itself pushes to window.dataLayer, no GTM/GA4 access needed at all;
  // distinct from GTM-13's version of the ghost-item failure, which is
  // about GTM's own trigger config rather than what the site pushes.
  { id: "WEB-57", title: "dataLayer ecommerce events missing entirely", expectedState: "Standard ecommerce events (view_item, add_to_cart, begin_checkout, purchase) pushed to window.dataLayer at the right journey points", commonFailure: "The site never wired the dataLayer plumbing at all — GA4/GTM would have nothing to listen to even if connected today", validate: "Live browser — trigger the actual journey (view product, add to cart, begin checkout) and read window.dataLayer directly for the expected event names — only evaluable when browser access is granted this run", severity: "critical" },
  { id: "WEB-58", title: "dataLayer ecommerce event schema incomplete", expectedState: "Each ecommerce event's `ecommerce.items` entries carry item_id/item_name/price/quantity, with currency and value at the event root", commonFailure: "Events push but with fields missing — imports broken data the moment tracking actually gets connected, often unnoticed since the event 'fires' successfully", validate: "Live browser — inspect the pushed dataLayer event's ecommerce object shape against GA4's Enhanced Ecommerce schema — only evaluable when browser access is granted this run", severity: "critical" },
  { id: "WEB-59", title: "Stale/ghost items in dataLayer ecommerce.items", expectedState: "ecommerce.items cleared between events, no items carried over from a previous push", commonFailure: "A recursive dataLayer merge (GTM's own docs warn about this exact bug) leaves items from a prior event still present in the next one — inflated/wrong item counts the moment tracking is connected", validate: "Live browser — push two different ecommerce events in sequence and confirm the second's ecommerce.items doesn't still contain the first's — only evaluable when browser access is granted this run", severity: "medium" },

  // Resource weight & delivery (WEB-60..WEB-63) — the four things the
  // removed PageSpeed category (PS-1..PS-4) actually scored, re-expressed
  // as real measurements off the headless browser's own network data
  // instead of a Lighthouse audit id. Same failures, same business framing,
  // no PageSpeed Insights round trip: the sweep those needed (a sequential
  // mobile+desktop PSI call per discovered page) was the single biggest
  // chunk of every run's wall-clock time. Byte counts come from each
  // response's own transfer size, which the browser reports directly.
  { id: "WEB-60", title: "Render-blocking scripts and stylesheets delay first paint", expectedState: "No synchronous <script src> in <head> without defer/async, and no more than a small handful of blocking stylesheets before first paint", commonFailure: "A blocking script or a stack of stylesheets in <head> holds the page blank while they download — every visitor pays that delay on every page, and a blank page during it is a bounce for a mobile visitor on a slow connection", validate: "The crawl's page source — count <script src> tags inside <head> carrying neither defer nor async, plus blocking <link rel=stylesheet> tags; confirm in the live browser which of those actually resolved before first contentful paint", severity: "medium" },
  { id: "WEB-61", title: "Oversized images shipped to visitors", expectedState: "No single image transferred over roughly 200KB, and no image whose natural pixel size is far larger than the box it renders in", commonFailure: "A full-resolution photo dropped straight into a CMS and downscaled by CSS ships every visitor bandwidth for pixels they never see — a default-upload mistake, not a one-off, and on a mobile-heavy GCC audience it costs both load time and the visitor's own mobile data", validate: "Live browser — from the network list, name every image response over ~200KB; then for the largest few compare naturalWidth/naturalHeight against the element's rendered clientWidth/clientHeight — only evaluable when browser access is granted this run", severity: "critical" },
  { id: "WEB-62", title: "Text responses served uncompressed", expectedState: "HTML, CSS, JS and JSON responses served with gzip or brotli compression", commonFailure: "Uncompressed text transfers several times more bytes than it needs to, on every single request, for the sake of a one-line server config — the cheapest speed win a site can have and the most commonly missed", validate: "Live browser — check the content-encoding response header on the main document and on the largest CSS/JS responses in the network list (the crawl's own captured headers already confirm the document one) — only fully evaluable when browser access is granted this run", severity: "medium" },
  { id: "WEB-63", title: "Oversized JavaScript/CSS payload on first load", expectedState: "First-load JS and CSS combined stay within a few hundred KB transferred, with no single bundle dominating it", commonFailure: "One shared mega-bundle ships checkout-page code to the homepage and vice versa — parse and execute time every visitor pays for code that page never runs, worst on the mid-range Android hardware most of this audience browses on", validate: "Live browser — sum the transfer size of every script and stylesheet response in the network list for the initial page load, and name the largest individual offenders — only evaluable when browser access is granted this run", severity: "medium" },
];

// The 25-item "website code" slice used on the single-tool route (visitor
// has exactly one of GA4/GTM — see scoring.ts's countedCategories): the
// tool they don't have isn't guessed at from public signal any more, it's
// replaced by a real, always-evaluable website-code audit instead. Picked
// by hand from WEBSITE_CHECKLIST for highest signal on exactly what this
// route is meant to catch that a live GA4/GTM check can't: dataLayer/
// ecommerce implementation (WEB-57/58/59), duplicate tag/event firing
// (WEB-17, WEB-59), consent mode (WEB-3, WEB-50), network-request
// anomalies (WEB-23/24/26), console errors (WEB-15/18/22/54), and resource
// weight/delivery (WEB-60..63) — all backed by the real headless-browser
// pass this route grants (mcp-config.ts's neededMcpServers.browser), same
// as the no-tools route below. `id in` filter (not a hand-copied second
// array) so the two lists can never drift apart on wording/severity for a
// shared id.
//
// Was 21 ids + the 4-point PageSpeed category until 2026-09-09; PageSpeed
// is gone (see this file's header) and WEB-60..63 — the browser-measured
// replacements for exactly what PS-1..PS-4 scored — take those four slots,
// so the route still totals 25 + 25 = 50.
const WEBSITE_CODE_CORE_IDS = new Set([
  "WEB-1", "WEB-2", "WEB-3", "WEB-4", "WEB-5", "WEB-13",
  "WEB-15", "WEB-16", "WEB-17", "WEB-18", "WEB-22",
  "WEB-23", "WEB-24", "WEB-26", "WEB-29", "WEB-32",
  "WEB-50", "WEB-54", "WEB-57", "WEB-58", "WEB-59",
  "WEB-60", "WEB-61", "WEB-62", "WEB-63",
]);

export const WEBSITE_CODE_CHECKLIST: ChecklistPoint[] = WEBSITE_CHECKLIST.filter(p => WEBSITE_CODE_CORE_IDS.has(p.id));

